### ISSUE TITLE
Task wakes too often in release mode when used with `async_std`

### ISSUE THREAD

**Issue by afeistel** [sdroege/async-tungstenite#133]
This may cause a CPU core to be constantly at `100%` after a client connects and sends nothing:

```rs
#[async_std::main]
async fn main() -> async_tungstenite::tungstenite::Result<()> {
    let listener = async_std::net::TcpListener::bind("127.0.0.1:8080").await?;
    let (stream, _) = listener.accept().await?;
    async_tungstenite::accept_async(stream).await?;
    Ok(())
}
```

(the same also happens after the handshake when the client is idle; using only `accept_async` as the example, because shorter)

It could be an issue with `async-std` but I haven't yet been able to replicate it without `async-tungstenite` ~~(both codebases are still a bit hard for me to navigate)~~.

```toml
[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
async-tungstenite = { version = "0.26.1", features = ["async-std-runtime"] }
```
