### ISSUE TITLE
Error using accept_async() with Tokio

### ISSUE THREAD

**Issue by inguar** [sdroege/async-tungstenite#25]
Hi! Wonderful crate. Everything I've tried so far works great, but there is one rough edge. I'm getting an error when trying to use `accept_async` with Tokio's `TcpStream`: 
```
error[E0277]: the trait bound `tokio::net::tcp::stream::TcpStream: futures_io::if_std::AsyncRead` is not satisfied
   --> src/main.rs:8:34
    |
8   |     let ws_stream = accept_async(stream).await.unwrap();
    |                                  ^^^^^^ the trait `futures_io::if_std::AsyncRead` is not implemented for `tokio::net::tcp::stream::TcpStream`
    | 
   ::: /Users/igor/.cargo/registry/src/github.com-1ecc6299db9ec823/async-tungstenite-0.4.2/src/lib.rs:142:8
    |
142 |     S: AsyncRead + AsyncWrite + Unpin,
    |        --------- required by this bound in `async_tungstenite::accept_async`
```
... and the same error with `AsyncWrite`. I suspect using Tokio has something to do with this. All uses of this function in examples rely on async-std's implementation.

----------

Here is a minimal example to reproduce the error:

**main.rs**
```rust
use async_tungstenite::accept_async;
use tokio::net::TcpListener;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut listener = TcpListener::bind("127.0.0.1:8080").await.unwrap();
    let Ok((stream, _)) = listener.accept().await;
    let ws_stream = accept_async(stream).await.unwrap();
    Ok(())
}
```
**Cargo.toml**
```toml
[package]
name = "async_fail"
version = "0.0.1"
edition = "2018"

[dependencies]
tokio = { version = "0.2.17", features = ["macros", "tcp", "dns", "io-util"] }
async-tungstenite = { version = "0.4.2", features = ["tokio-tls", "tokio-runtime"] }
```
